#!/bin/bash
#https://gist.github.com/tlberglund/3714970
#Is your log longer than the terminal window? Sometimes I'll run it with a commit limit (`git loglive -15`) to help things fit.

while :
do
    clear
    git --no-pager log --graph --pretty=oneline --abbrev-commit --decorate --all $*
    sleep 1
done
